### ISSUE TITLE
Code on documentation website is not legible

### ISSUE THREAD

**Issue by slimetree** [fukamachi/clack#104]
The selector `.highlighter-coderay .CodeRay .code pre` has `background-color: #1d1f21` which makes it illegible.

**Comment by slimetree** [comment]
(I keep disabling it with Inspector.)

**Comment by eudoxia0** [comment]
Can you show us a screenshot? Exactly what website is this, since clacklisp.com uses [highlight-lisp](https://github.com/orthecreedence/highlight-lisp), not CodeRay.

**Comment by fukamachi** [comment]
Like this? 

![screen shot 2015-04-09 at 10 26 22 am](https://cloud.githubusercontent.com/assets/90570/7058886/ead1695e-dea2-11e4-9037-54300ba237ca.png)

http://clacklisp.org/tutorial/03-hello-world.html

As I don't see any CodeRay styles in the markdown, probably Jekyll is doing something.

**Comment by eudoxia0** [comment]
Ok, here's the thing, Jekyll is highlighting the blocks because they are marked up as being Lisp, since it doesn't know we're using highlight-lisp. Probably a version change.

The solution is to find an option to disable highlighting.

**Comment by fukamachi** [comment]
I've regenerated them with the latest Jekyll, and then it looks fine now.
