### ISSUE TITLE
Component tutorial not working

### ISSUE THREAD

**Issue by siriustnt** [fukamachi/clack#107]
I tried following this tutorial http://clacklisp.org/tutorial/05-component.html

	(ql:quickload :clack-v1-compat)
	(defpackage web
	  (:use :cl))
	(in-package :web)

	;; importing symbols for readability.
	(import '(clack:call clack:<component>))

	(defclass <sample-app> (<component>) ())

	(defmethod call ((this <sample-app>) env)
	  (declare (ignore env))
	  '(200
		(:content-type "text/plain")
		("Hello, Clack!")))

	(defparameter *app* (make-instance '<sample-app>))
	(clack:clackup *app*)

But it gives me the following error:

	#<<SAMPLE-APP> {1003ADB693}> fell through ETYPECASE expression. Wanted one of ((OR PATHNAME STRING) FUNCTION).

Which makes sense because the ETYPECASE in clackup doesn't handle a class. Is this a bug or am I just doing something wrong?

**Comment by Rudolph-Miller** [comment]
The commit https://github.com/fukamachi/clack/commit/696dcefc75a0b374d926c4faa22b6fba93f40854 looks to fix this issue.

**Comment by fukamachi** [comment]
Right. I suppose it has been already fixed.
