### ISSUE TITLE
how to store sessions in database ?

### ISSUE THREAD

**Issue by mateuszb** [fukamachi/clack#110]
I have the following line in the builder part of app.lisp file.
```
(<clack-middleware-session>
  :store (make-instance 'clack.session.store.dbi:<clack-session-store-dbi>
                        :connect-args '(:postgresql
					:database-name "DBNAME"
					:username "ROLE"
					:password "PASSWORD")))
```
also added clack.session.store.dbi to depends-on section in ASD file but it seems like the dbi storage of sessions is actually removed from the software altogether?

What's the preferred way to store sessions in database ?

**Comment by fukamachi** [comment]
It seems clack.session.store.dbi was accidentally deleted at 7cce17aa616dfd72cdc79c431ac5054918df97a8 and forgot to revert it.

**Comment by fukamachi** [comment]
clack-session-store-dbi is now loadable in the latest Clack.
Feel free to reopen this if you still have some problems.
