### ISSUE TITLE
Trivial way to cause crash even in production/non-debug mode (urlencoded characters)

### ISSUE THREAD

**Issue by ahungry** [fukamachi/clack#111]
Make a site start up such as:
```lisp
(ql:quickload :com.ahungry)
(com.ahungry:start :server :woo :port 12345)
```

Then make a request into one of the static serve directories, such as:
```sh
curl 'http://localhost:12345/css/%3Fbroken=yup'
```

Server will then bring up an error, which then causes a segfault.

A call to #'start again will print that the server is still running (and require choice 0, a restart), but the server will be completely unresponsive to future requests.

The error is that it fails to physicalize the pathname (it turns %3F into a ?, which breaks the path name, as the ? is normally parsed out before it gets that far in a proper URL request).

**Comment by ahungry** [comment]
This is not clack specific beyond mitigating this issue until a fix is applied, but it can be remedied on a firewall level with the following (adjust as needed):
```sh
iptables -I INPUT -p tcp --dport 12345 -m string --algo bm --from 0 --to 1500 --string "%3F" -j DROP
```

If doing proxy passing from port 80 to your clack instance, you can change 12345 to port 80 (or 443) as necessary.

**Comment by fukamachi** [comment]
I'll close this when #113 has been merged.

**Comment by fukamachi** [comment]
Thank you for reporting!

It turned out that the problem was in clack.middleware.static & lack.middleware.static.
I believe it has been fixed now.

Feel free to reopen this if you still have some problems.

**Comment by ahungry** [comment]
Thanks - stellar work as always!
