### ISSUE TITLE
Unknown SIMPLE-ERROR leading to a deadlock in clack-handler-woo

### ISSUE THREAD

**Issue by ahungry** [fukamachi/clack#116]
Running my site for awhile, it eventually hits this error:

```sh
debugger invoked on a SIMPLE-ERROR in thread
#<THREAD "clack-handler-woo" RUNNING {10079586B3}>:
  Can't accept connection (Code: 24)
```

Unfortunately it doesn't print a backtrace for me to give any more information, so I'm not sure if it's a woo issue or clack issue.

The site gets a couple hundred hits (AJAX requests, dispatched by web.lisp in caveman) per minute, so pretty heavy traffic when it's up.

I didn't see the string "Can't accept connection" in caveman or clack source, so I'll check woo next.

**Comment by Rudolph-Miller** [comment]
In our company, the server using Woo and Clack handles 1 thousand requests per minute per one server, and I saw the same message (it actually emitted by Woo) in the past ( NOW it works well ).
I solved the problem without changing Woo itself.

I can not recall what I did certainly.

**Comment by Rudolph-Miller** [comment]
`Code: 24` means `Too many files`, so you have to check how many files a process can open with `ulimit -n` and you may have to increase the max by some methods. (one way is to edit `/etc/security/limits.conf` https://rtcamp.com/tutorials/linux/increase-open-files-limit/)

**Comment by ahungry** [comment]
Thanks @Rudolph-Miller ! Mine is currently set to 1024 - I wonder if it's tied to the CLACK.SESSION storage (and having more than 1024 users with open sessions at a time).

I'll up it to an unapprochable number and see if it fixes the issue.

**Comment by Rudolph-Miller** [comment]
You're welcome. : )

I hope it can fix the issue.

**Comment by ahungry** [comment]
That definitely seems to be the problem.  Now, since I'm not actually using the sessions at this time, I should probably disable them for (hopefully) some optimization to the site.

Closing the issue, as this definitely seems like it was OS related and not clack/woo specific.

Thanks again!

**Comment by Rudolph-Miller** [comment]
That's my pleasure to hear it. : )
