### ISSUE TITLE
clack hello world don't work

### ISSUE THREAD

**Issue by leiding** [fukamachi/clack#120]
I can't execute the simple hello world code after install clack

```
(clack:clackup
  (lambda (env)
    (declare (ignore env))
    '(200 (:content-type "text/plain") ("Hello, Clack!"))))

Error stack:
There is no applicable method for the generic function
  #<STANDARD-GENERIC-FUNCTION
    (SETF HUNCHENTOOT::ACCEPTOR-PROCESS) (1)>
when called with arguments
  (NIL #<HUNCHENTOOT:SINGLE-THREADED-TASKMASTER {12BCE779}>).
   [Condition of type SIMPLE-ERROR]

Restarts:
 0: [RETRY] Retry calling the generic function.
 1: [RETRY] Retry SLIME REPL evaluation request.
 2: [*ABORT] Return to SLIME's top level.
 3: [REMOVE-FD-HANDLER] Remove #<SB-IMPL::HANDLER INPUT on descriptor 21: #<CLOSURE (LABELS SWANK/SBCL::RUN :IN SWANK/BACKEND:ADD-FD-HANDLER) {12BFB535}>>
 4: [ABORT] Exit debugger, returning to top level.

Backtrace:
  0: ((:METHOD NO-APPLICABLE-METHOD (T)) #<STANDARD-GENERIC-FUNCTION (SETF HUNCHENTOOT::ACCEPTOR-PROCESS) (1)> NIL #<HUNCHENTOOT:SINGLE-THREADED-TASKMASTER {12BCE779}>) [fast-method]
      Locals:
        SB-PCL::ARGS = (NIL #<HUNCHENTOOT:SINGLE-THREADED-TASKMASTER {12BCE779}>)
        GENERIC-FUNCTION = #<STANDARD-GENERIC-FUNCTION (SETF HUNCHENTOOT::ACCEPTOR-PROCESS) (1)>
  1: (SB-PCL::CALL-NO-APPLICABLE-METHOD #<STANDARD-GENERIC-FUNCTION (SETF HUNCHENTOOT::ACCEPTOR-PROCESS) (1)> (NIL #<HUNCHENTOOT:SINGLE-THREADED-TASKMASTER {12BCE779}>))
      Locals:
        SB-DEBUG::ARG-0 = #<STANDARD-GENERIC-FUNCTION (SETF HUNCHENTOOT::ACCEPTOR-PROCESS) (1)>
        SB-DEBUG::ARG-1 = (NIL #<HUNCHENTOOT:SINGLE-THREADED-TASKMASTER {12BCE779}>)
  2: (CLACK.HANDLER.HUNCHENTOOT:RUN #<CLOSURE (LAMBDA (LACK.MIDDLEWARE.BACKTRACE::ENV) :IN "/Users/leiding/quicklisp/dists/quicklisp/software/lack-20150709-git/src/middleware/backtrace.lisp") {1385BC1D}> :..
      Locals:
        APP = #<CLOSURE (LAMBDA (LACK.MIDDLEWARE.BACKTRACE::ENV) :IN "/Users/leiding/quicklisp/dists/quicklisp/software/lack-20150709-git/src/middleware/backtrace.lisp") {1385BC1D}>
        #:DEBUG-DEFAULTING-TEMP = T
        #:MAX-ACCEPT-COUNT-DEFAULTING-TEMP = NIL
        #:MAX-THREAD-COUNT-DEFAULTING-TEMP = NIL
        #:PERSISTENT-CONNECTIONS-P-DEFAULTING-TEMP = T
        #:PORT-DEFAULTING-TEMP = 5000
        #:SSL-CERT-FILE-DEFAULTING-TEMP = NIL
        #:SSL-DEFAULTING-TEMP = NIL
        #:SSL-KEY-FILE-DEFAULTING-TEMP = NIL
        #:SSL-KEY-PASSWORD-DEFAULTING-TEMP = NIL
  3: (CLACK.HANDLER:RUN #<CLOSURE (LAMBDA (LACK.MIDDLEWARE.BACKTRACE::ENV) :IN "/Users/leiding/quicklisp/dists/quicklisp/software/lack-20150709-git/src/middleware/backtrace.lisp") {1385BC1D}> :HUNCHENTOOT ..
  4: (CLACK:CLACKUP #<FUNCTION (LAMBDA (ENV)) {150C52AD}>)
  5: (SB-INT:SIMPLE-EVAL-IN-LEXENV (CLACK:CLACKUP (LAMBDA (ENV) (DECLARE (IGNORE ENV)) (QUOTE (200 (:CONTENT-TYPE "text/plain") ("Hello, Clack!"))))) #<NULL-LEXENV>)
  6: (EVAL (CLACK:CLAC
```

**Comment by fukamachi** [comment]
Could you tell me the following information?

- The return value of `(ql-dist:dist "quicklisp")`
- The output of `(ql:quickload :repl-utilities) (repl-utilities:dependency-locations :clack t)`
- The return value of `(find :sb-thread *features*)`

**Comment by leiding** [comment]
CL-USER> (ql-dist:dist "quicklisp")
#<DIST quicklisp 2015-07-10>

CL-USER> (repl-utilities:dependency-locations :clack t)
#P"/Users/leiding/quicklisp/dists/quicklisp/software/clack-20150709-git/", clack
#P"/Users/leiding/quicklisp/dists/quicklisp/software/lack-20150709-git/", lack
#P"/Users/leiding/quicklisp/dists/quicklisp/software/lack-20150709-git/", lack-component
#P"/Users/leiding/quicklisp/dists/quicklisp/software/lack-20150709-git/", lack-util
#P"/Users/leiding/quicklisp/dists/quicklisp/software/ironclad_0.33.0/", ironclad
#P"/usr/local/lib/sbcl/sb-rotate-byte/", sb-rotate-byte
#P"/usr/local/lib/sbcl/sb-posix/", sb-posix
#P"/usr/local/lib/sbcl/sb-grovel/", sb-grovel
#P"/Users/leiding/quicklisp/dists/quicklisp/software/nibbles-20150709-git/", nibbles
#P"/Users/leiding/quicklisp/dists/quicklisp/software/alexandria-20150505-git/", alexandria
#P"/Users/leiding/quicklisp/dists/quicklisp/software/bordeaux-threads-0.8.3/", bordeaux-threads

CL-USER> (find :sb-thread *features*)
NIL

**Comment by leiding** [comment]
Thanks for quick fix.

**Comment by leiding** [comment]
One quick question How could I get the fix with quick lisp? I am using (ql:quickload :clack) to get clack

**Comment by fukamachi** [comment]
To use the latest version of Clack, download from GitHub and put it to a directory ASDF can find:

```
cd ~/common-lisp
git clone https://github.com/fukamachi/clack
```

**Comment by leiding** [comment]
I just try the latest code and the hello world still not work. It hangs there.
* (ql:quickload "clack")
To load "clack":
  Load 1 ASDF system:
    clack
; Loading "clack"
..................................................
[package clack.util]..............................
[package clack.handler]...........................
[package clack]...................................
[package clack]...................................
[package clack].
("clack")
* (clack:clackup
  (lambda (env)
    (declare (ignore env))
    '(200 (:content-type "text/plain") ("Hello, Clack!"))))

Hunchentoot server is going to start.
Listening on localhost:5000.
To load "lack-middleware-backtrace":
  Load 1 ASDF system:
    lack-middleware-backtrace
; Loading "lack-middleware-backtrace"

To load "clack-handler-hunchentoot":
  Load 1 ASDF system:
    clack-handler-hunchentoot
; Loading "clack-handler-hunchentoot"
..................................................
[package clack.handler.hunchentoot].

**Comment by fukamachi** [comment]
I assume you're using SBCL without thread support. Then, it works. Open localhost:5000 on your browser.

**Comment by leiding** [comment]
Yes, I verified with localhost:5000 and nothing return. 
I am recompiling sbcl with thread support now.

**Comment by fukamachi** [comment]
Did you get any errors at your REPL when you open the page?

**Comment by leiding** [comment]
No

**Comment by fukamachi** [comment]
What do you get by `curl -v http://127.0.0.1/`?

**Comment by leiding** [comment]
Sorry, I already switched to sbcl with thread supported. I will give more detailed info in another setup. Any other output do you want?

**Comment by fukamachi** [comment]
There's no differences in the behavior between thread-support version and no thread one except whether REPL is available after starting a server. 

Give me the response of curl and error details if you get any errors.

**Comment by leiding** [comment]
Thanks, I think I got the problem. There is a proxy in my browser. curl -v http://127.0.0.1 works.
And in the production environment which run clack, we must configure sbcl to support thread right?

**Comment by fukamachi** [comment]
It depends on your setup, but I think you don't need thread-support of SBCL on the production environment since the process runs only an HTTP server. It will serve pages even after its REPL hangup.

**Comment by fukamachi** [comment]
If you're thinking of using Hunchentoot in your production environment (I don't recommend it, though), you may want to use thread-support one because it performs better with multi-threaded SBCL.
