### ISSUE TITLE
One of these cookies caused Clack to throw an error

### ISSUE THREAD

**Issue by FungusHumungus** [fukamachi/clack#123]
Running Clack through Caveman2, I had the following cookies on localhost:

"outlet=%5Bobject%20Object%5D; __ngDebug=false; sets=eyJwYXNzcG9ydCI6eyJ1c2VyIjoxfX0=; sets.sig=sRQEx-o2I8PR63rAIOCySgrXavQ; ring-session=150e1b24-7e6f-44af-b858-6f745725f469"

This causes Clack to throw a QURI.ERROR:URI-MALFORMED-URLENCODED-STRING error which then stops the request from being processed.

**Comment by fukamachi** [comment]
Needs more information:

* Actual stack trace.
* Quicklisp dist version.
* Git commit ref if you have a local copy of QURI or Lack.

And try the following code and give me the result. It's a short snippet parsing the cookie string like Lack.Request does.

```common-lisp
(ql:quickload '(:quri :cl-ppcre))

(mapcar (lambda (kv) (quri:url-decode-params kv :lenient t))
        (ppcre:split "\\s*[,;]\\s*" "outlet=%5Bobject%20Object%5D; __ngDebug=false; sets=eyJwYXNzcG9ydCI6eyJ1c2VyIjoxfX0=; sets.sig=sRQEx-o2I8PR63rAIOCySgrXavQ; ring-session=150e1b24-7e6f-44af-b858-6f745725f469"))
```

**Comment by FungusHumungus** [comment]
Apologies, it was very late at night and I wasn't thinking clearly when I raised this issue. I will dig into it further and provide more information shortly.

**Comment by FungusHumungus** [comment]
I am a numpty, I just needed to update my packages. All works fine now. Sorry for the bother!
