### ISSUE TITLE
Clack version confusion

### ISSUE THREAD

**Issue by mmontone** [fukamachi/clack#124]
Hello @fukamachi 

I'm trying to get started with Clack, but I see there's a new version (version 2, I guess) and also see frameworks like Lucerne use clack-v1-compat system, etc. I'm not sure what I should be using. I suppose the new version relies on Lack, and doesn't provide the old clack.request, etc packages.

Can you guide me a bit?

Thanks!

**Comment by fukamachi** [comment]
clack-v1-compat is only for old projects like Lucerne and I recommend to use Clack v2 API for new projects. ningle and Caveman2 were used to use Clack v1, however, they had been already migrated.

> I suppose the new version relies on Lack, and doesn't provide the old clack.request, etc packages.

Although I don't get what you mean exactly, Lack also provides Lack.Request ([lack-request.asd](https://github.com/fukamachi/lack/blob/master/lack-request.asd)) as a separated system, though its APIs are different from v1's.

**Comment by mmontone** [comment]
Thanks! Things are a bit clearer for me now.
