### ISSUE TITLE
Underscore in character names should by hyphen for Lispworks 7.x+

### ISSUE THREAD

**Issue by dbmcclain** [fukamachi/clack#162]
Line 252 of file src/handler/hunchentoot.lisp refers to character #Replacement_Character. This was intended to work for all but ABCL. SBCL properly recognizes an underscore convention. But Lispworks 7.x+ does not. It uses hyphenated character names.

For myself, I have replaced the lines with:
```
  (let ((flex:*substitution-char* #+lispworks #\Replacement-Character
                                  #+abcl #\?
                                  #-(OR :abcl :lispworks) #\Replacement_Character)
```

**Comment by fukamachi** [comment]
I think this is already resolved at https://github.com/fukamachi/clack/pull/150.
