### ISSUE TITLE
Some systems failed to build for Quicklisp dist

### ISSUE THREAD

**Issue by quicklisp** [fukamachi/clack#172]
Building with SBCL 2.2.1 / ASDF 3.3.5 for quicklisp dist creation.

Trying to build commit id 9bdc012b3bf24988957877bf7b0f5c00a81a82cf

*clack-test* fails to build with the following error:

```
; caught ERROR:
;   READ error during COMPILE-FILE: Package IRONCLAD does not exist. Line: 526, Column: 49, File-Position: 20872 Stream: #<SB-INT:FORM-TRACKING-STREAM for "file /home/quicklisp/quicklisp-controller/dist/build-cache/clack/68f7131ac7b44c672dcec71f8bbee1b2182761e7/clack-20220210-git/src/test/suite.lisp" {1017625EE3}>
...
Unhandled UIOP/LISP-BUILD:COMPILE-FILE-ERROR in thread #<SB-THREAD:THREAD "main thread" RUNNING {1001B98003}>: COMPILE-FILE-ERROR while compiling #<CL-SOURCE-FILE "clack-test" "src/test/suite">

```

*t-clack-handler-fcgi* fails to build because of a failure in  _clack-test_.

*t-clack-handler-hunchentoot* fails to build because of a failure in  _clack-test_.

*t-clack-handler-toot* fails to build because of a failure in  _clack-test_.

*t-clack-handler-wookie* fails to build because of a failure in  _clack-test_.

[Full log here](http://report.quicklisp.org/2022-02-10/failure-report/clack.html)

**Comment by fukamachi** [comment]
Thanks for reporting.
It was the effect of changes in Lack, and I think it has resolved at 6fd0279424f7ba5fd4f92d69a1970846b0b11222.
