### ISSUE TITLE
Adding a link to the blog post

### ISSUE THREAD

**Issue by joshcho** [fukamachi/clack#178]
Currently there is no documentation on the project, and the closest thing I have seen is https://fukamachi.hashnode.dev/how-to-build-a-web-app-with-clack-and-lack-1. It would be helpful for newcomers to be linked to that.

EDIT: I have also found https://github.com/jasom/clack-tutorial/blob/src/pages/getting-started-with-clack.org to be helpful.

**Comment by fukamachi** [comment]
Thank you for pointing it out.
I'm going to add them.
