### ISSUE TITLE
Seems, Hunchentoot handler was broken in latest version of Clack

### ISSUE THREAD

**Issue by svetlyak40wt** [fukamachi/clack#186]
I'm experiencing problems after upgrate to , Ultralisp was broken.

When a test Clack server is started using Hunchentoot:

```lisp
(defvar *handler* nil)

(defun run-test-app ()
  (setf *handler*
        (clack:clackup
         (lambda (env)
           (declare (ignore env))
           '(200 (:content-type "text/plain") ("Hello, Clack!")))
         :server :hunchentoot
         :address "0.0.0.0"
         :port 80)))
```

I'm getting this `404 Not Found The requested URL / was not found on this server.` error in the browser.

But if I change `:hunchentoot` with `:woo`. It works!

Tested on Clack installed from Ultralisp version 20230323053129.

**Comment by K1D77A** [comment]
Yep just noticed this while deploying a new version of a commercial project :facepalm:

**Comment by svetlyak40wt** [comment]
Probably we need some sort of smoking test here? Just to ensure that server
can be started using all kinds of implementation.

чт, 30 мар. 2023 г., 08:25 Josh Betts ***@***.***>:

**Comment by K1D77A** [comment]
Maybe was this merge? https://github.com/fukamachi/clack/commit/739598fc8339fd56d930fd515e192fe7756753b7

**Comment by fukamachi** [comment]
Closing this because it's already fixed, I suppose.
Feel free to reopen this if you still have the problem.
