### ISSUE TITLE
regression - fails to load on ABCL

### ISSUE THREAD

**Issue by avodonosov** [fukamachi/clack#74]
Something changed in clack since quicklisp 2014-07-14, and now clack and all the dependent libraries fail to load on ABCL

See diff between quicklisp 2014-07-14 and qlalpha 2014-08-23:
http://common-lisp.net/project/cl-test-grid/ql/qlalpha-2014-08-23-diff.html

The error: 
```
SIMPLE-TYPE-ERROR : The value of BORDEAUX-THREADS::LOCK is #S(BORDEAUX-THREADS::MUTEX :NAME "Anonymous lock" :LOCK #<java.util.concurrent.locks.ReentrantLock java.util.concurrent.locks.Reent.... {B46184}>), which is not of type BORDEAUX-THREADS::MUTEX-RECURSIVE.
```
Strange that it happens during load time.

**Comment by fukamachi** [comment]
I think this problem has already been resolved after merging #95.
