### ISSUE TITLE
HTTPS support via SSL

### ISSUE THREAD

**Issue by resttime** [fukamachi/clack#75]
Would it be possible to see support for HTTPS with SSL
Hunchentoot is used as one of the server handlers which supports it.
Also, I'm a novice at lisp but I would be willing to try my best to implement the feature.

Also, I really like Clack. Thank you for making it!

**Comment by fukamachi** [comment]
I think we can use FastCGI handler with SSL by make the bypass server (like nginx) allow SSL connections and no need to support in the handler layer.
Though [Woo](https://github.com/fukamachi/woo) is the only server doesn't support SSL, it should be implemented in the server itself.
So, there's no tasks left to do. Closing.

**Comment by fosskers** [comment]
A well-viewed post of Stackoverflow links to this issue, so I will also link [this Woo issue](https://github.com/fukamachi/woo/issues/4) for anyone else who wanders in here.

**Comment by jackcarrozzo** [comment]
I have used nginx reverse-proxy with clack and friends to do SSL, works extremely well.

**Comment by fosskers** [comment]
That approach has definitely occurred to me but I'm still holding out for an all-in-CL solution (that isn't Hunchentoot).
