### ISSUE TITLE
clack-handler-wookie does not build - symbol issue?

### ISSUE THREAD

**Issue by quicklisp** [fukamachi/clack#99]
I don't understand the error I'm getting in http://report.quicklisp.org/2015-03-01/failure-report/clack.html#clack-handler-wookie - 

    ; caught ERROR:
    ;   READ error during COMPILE-FILE: Package LOG does not exist.Line: 81, Column: 15, File-Position: 2517Stream: #<SB-SYS:FD-STREAM for "file /home/quicklisp/quicklisp-controller/dist/build-cache/clack/306da87217862069f5fa54167780045e54450d9d/clack-20150302-git/src/core/handler/wookie.lisp"

**Comment by Rudolph-Miller** [comment]
`log4cl` seems not to be loaded.

**Comment by Rudolph-Miller** [comment]
Now `wookie` doesn't use `log4cl`, we remove `(log:config ...)` lines, can't we?

**Comment by fukamachi** [comment]
@quicklisp Thanks for the report.

I've fixed the symbol issue by simply deleting `log:config` code.
However, the tests of clack.handler.wookie failed on Travis CI with the latest Wookie. It doesn't look the same error, but I don't know why yet.
It might be a problem of dependency updates Wookie is using.

Could you please try loading it again?

**Comment by fukamachi** [comment]
I assume the problem has been fixed. Closing.
